# Podman Compose configuration optimized for test environments
# Resource limits are reduced for faster startup and lower resource consumption
# Restart policy is set to "no" to ensure clean teardown after tests
version: "3.9"

services:
  crypto-scout-collector-db:
    image: timescale/timescaledb:latest-pg17
    container_name: crypto-scout-collector-db
    cpus: "1.00"
    mem_limit: "2g"
    mem_reservation: "1g"
    shm_size: "256m"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/00_init.sql:ro
      - ./script/bybit_spot_tables.sql:/docker-entrypoint-initdb.d/01_bybit_spot_tables.sql:ro
      - ./script/bybit_linear_tables.sql:/docker-entrypoint-initdb.d/02_bybit_linear_tables.sql:ro
      - ./script/crypto_scout_tables.sql:/docker-entrypoint-initdb.d/03_crypto_scout_tables.sql:ro
    environment:
      TZ: UTC
      POSTGRES_DB: crypto_scout
      POSTGRES_USER: crypto_scout_db
      POSTGRES_PASSWORD: crypto_scout_db
      POSTGRES_EXTRA_OPTS: --schema=crypto_scout --blobs
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    command:
      - postgres
      - -c
      - shared_preload_libraries=timescaledb,pg_stat_statements
      - -c
      - max_connections=50
      - -c
      - shared_buffers=128MB
      - -c
      - effective_cache_size=256MB
      - -c
      - maintenance_work_mem=64MB
      - -c
      - work_mem=4MB
      - -c
      - autovacuum_work_mem=64MB
      - -c
      - wal_level=replica
      - -c
      - max_wal_size=1GB
      - -c
      - min_wal_size=256MB
      - -c
      - checkpoint_timeout=5min
      - -c
      - checkpoint_completion_target=0.9
      - -c
      - wal_compression=on
      - -c
      - timezone=UTC
      - -c
      - log_min_duration_statement=-1
      - -c
      - log_checkpoints=off
      - -c
      - timescaledb.telemetry_level=off
      - -c
      - pg_stat_statements.track=all
      - -c
      - pg_stat_statements.max=10000
      - -c
      - timescaledb.max_background_workers=64
      - -c
      - max_worker_processes=80
      - -c
      - track_io_timing=on
      - -c
      - track_functions=pl
    restart: "no"
    stop_graceful_period: 30s

  crypto-scout-mq:
    image: rabbitmq:4.1.4-management
    container_name: crypto-scout-mq
    hostname: crypto_scout_mq
    ports:
      - "127.0.0.1:5672:5672"   # AMQP protocol
      - "127.0.0.1:5552:5552"   # Stream protocol (required for RabbitMQ streams)
    volumes:
      - "./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro"
      - "./rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro"
      - "./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro"
    environment:
      TZ: UTC
      RABBITMQ_ERLANG_COOKIE: CRYPTO_SCOUT_MQ_COOKIE_2026
    cpus: "1.0"
    user: "rabbitmq:rabbitmq"
    mem_limit: "512m"
    mem_reservation: "256m"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: "no"
    security_opt:
      - no-new-privileges=true
    init: true
    pids_limit: 512
    stop_signal: SIGTERM
    tmpfs:
      - /tmp:rw,size=32m,mode=1777,nodev,nosuid
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    stop_graceful_period: 30s
